### ISSUE TITLE
Image is broken

### ISSUE THREAD

**Issue by ewyler** [iocost-benchmark/iocost-benchmarks#82] opened 2024-02-14 17:11 UTC

**Comment by santoshmahto7** [comment] 2024-02-14 17:38
Now it's confirmed, the image is using resctl-demo available in [crates.io](https://crates.io/crates/resctl-demo)
So publishing new version in crates.io will solve the broken image problem.
@htejun : I don't seems to have permission to login with organization permission. Could you confirm if you want to do it ?

**Comment by santoshmahto7** [comment] 2024-02-23 07:02
PR:
1. wait unit boot partition is recognised and also debugging 
  - https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/39
  
2. Make pivot as default option
 - https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/40

**Comment by obbardc** [comment] 2024-07-18 12:46
duplicate of [resctl-demo-image-recipe#](https://github.com/iocost-benchmark/resctl-demo-image-recipe/issues/35)

**Closed by obbardc** 2024-07-18 12:46 UTC
